# Álgebra Linear com NumPy

Este notebook apresenta os principais conceitos de **álgebra linear** utilizando a biblioteca `NumPy`, fundamental para computação numérica em Python. Vamos abordar:

- Estruturas de dados: Escalares, Vetores, Matrizes e Tensores
- Operações: Adição, Produto, Produto Elemento a Elemento, Transposição

In [5]:
import numpy as np

escalar = np.array(5)
print("Escalar:", escalar)
print("Forma:", escalar.shape)
print("Tipo:", escalar.dtype)


Escalar: 5
Forma: ()
Tipo: int64


### 2. Vetores

Um **vetor** é um array unidimensional de números.

In [6]:
# criar um vetor linha no numpy
vetor_linha = np.array([[1, 2, 3]])
print("Vetor Linha:", vetor_linha)
print("Forma:", vetor_linha.shape)

# criar um vetor coluna no numpy
vetor_coluna = np.array([[1], [2], [3]])
print("Vetor Coluna:\n", vetor_coluna)
print("Forma:", vetor_coluna.shape)

Vetor Linha: [[1 2 3]]
Forma: (1, 3)
Vetor Coluna:
 [[1]
 [2]
 [3]]
Forma: (3, 1)


### 3. Matrizes

Uma **matriz** é um array bidimensional de números.

In [7]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz:\n", matriz)
print("Forma:", matriz.shape)


Matriz:
 [[1 2 3]
 [4 5 6]]
Forma: (2, 3)


### 4. Tensores

Um **tensor** é uma generalização de vetores e matrizes para mais de 2 dimensões.

In [8]:
tensor = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]]
])
print("Tensor:\n", tensor)
print("Forma:", tensor.shape)


Tensor:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Forma: (2, 3, 2)
