# Álgebra Linear com NumPy

Este notebook apresenta os principais conceitos de **álgebra linear** utilizando a biblioteca `NumPy`, fundamental para computação numérica em Python. Vamos abordar:

- Estruturas de dados: Escalares, Vetores, Matrizes e Tensores
- Operações: Adição, Produto, Produto Elemento a Elemento, Transposição

In [2]:
import numpy as np

escalar = np.array(5)
print("Escalar:", escalar)
print("Forma:", escalar.shape)
print("Tipo:", escalar.dtype)


Escalar: 5
Forma: ()
Tipo: int64


### 2. Vetores

Um **vetor** é um array unidimensional de números.

In [3]:
# criar um vetor linha no numpy
vetor_linha = np.array([[1, 2, 3]])
print("Vetor Linha:", vetor_linha)
print("Forma:", vetor_linha.shape)

# criar um vetor coluna no numpy
vetor_coluna = np.array([[1], [2], [3]])
print("Vetor Coluna:\n", vetor_coluna)
print("Forma:", vetor_coluna.shape)

Vetor Linha: [[1 2 3]]
Forma: (1, 3)
Vetor Coluna:
 [[1]
 [2]
 [3]]
Forma: (3, 1)


### 3. Matrizes

Uma **matriz** é um array bidimensional de números.

In [4]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz:\n", matriz)
print("Forma:", matriz.shape)


Matriz:
 [[1 2 3]
 [4 5 6]]
Forma: (2, 3)


### 4. Tensores

Um **tensor** é uma generalização de vetores e matrizes para mais de 2 dimensões.

In [5]:
tensor = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]]
])
print("Tensor:\n", tensor)
print("Forma:", tensor.shape)


Tensor:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Forma: (2, 3, 2)


## Operações Básicas

Agora vamos realizar operações fundamentais de álgebra linear com NumPy nessas estruturas.

### Adição

**Vetores:**

In [6]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v_soma = v1 + v2
print("Soma de Vetores:", v_soma)


Soma de Vetores: [5 7 9]


**Matrizes:**

In [7]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
m_soma = m1 + m2
print("Soma de Matrizes:\n", m_soma)


Soma de Matrizes:
 [[ 6  8]
 [10 12]]


### Produto Elemento a Elemento

**Vetores:**

In [8]:
v_produto = v1 * v2
print("Produto Elemento a Elemento de Vetores:", v_produto)


Produto Elemento a Elemento de Vetores: [ 4 10 18]


**Matrizes:**

In [9]:
m_produto = m1 * m2
print("Produto Elemento a Elemento de Matrizes:\n", m_produto)


Produto Elemento a Elemento de Matrizes:
 [[ 5 12]
 [21 32]]


### Transposição

**Vetor Transposto:**

In [10]:
print("Vetor linha original:\n", vetor_linha)
vetor_transposto = vetor_linha.T
print("Vetor Transposto:\n", vetor_transposto)

Vetor linha original:
 [[1 2 3]]
Vetor Transposto:
 [[1]
 [2]
 [3]]


**Matriz Transposta:**

In [11]:
print("Matriz Original:\n", m1)
m_transposta = m1.T
print("Matriz Transposta:\n", m_transposta)


Matriz Original:
 [[1 2]
 [3 4]]
Matriz Transposta:
 [[1 3]
 [2 4]]


**Transposição de Tensor (troca de eixos):**

In [12]:
print("Forma Original do Tensor:", tensor.shape)
tensor_transposto = np.transpose(tensor, axes=(1, 0, 2))
print("Forma do Tensor Transposto:", tensor_transposto.shape)
print("Tensor Transposto:\n", tensor_transposto)


Forma Original do Tensor: (2, 3, 2)
Forma do Tensor Transposto: (3, 2, 2)
Tensor Transposto:
 [[[ 1  2]
  [ 7  8]]

 [[ 3  4]
  [ 9 10]]

 [[ 5  6]
  [11 12]]]


### Produto Escalar

O **produto escalar** é uma operação fundamental em álgebra linear e em muitos modelos de machine learning.

In [13]:
produto_escalar = np.dot(v1, v2)
print("Produto Escalar (Vetores):", produto_escalar)


Produto Escalar (Vetores): 32


In [14]:
produto_matrizes = np.dot(m1, m2)
print("Produto de Matrizes:\n", produto_matrizes)


Produto de Matrizes:
 [[19 22]
 [43 50]]


In [15]:
produto_mv = np.dot(m1, v1[:2])  # ajustando as dimensões
print("Produto Matriz x Vetor:\n", produto_mv)


Produto Matriz x Vetor:
 [ 5 11]


### Produto Escalar de Matrizes - Passo a Passo

 Demonstrar o produto escalar (multiplicação) das matrizes `m1` e `m2` passo a passo. A multiplicação de matrizes $A \times B$ é definida se o número de colunas de $A$ for igual ao número de linhas de $B$. A dimensão da matriz resultante será (número de linhas de $A$) x (número de colunas de $B$).

Neste caso, temos:
`m1` (2x2) e `m2` (2x2). O número de colunas de `m1` (2) é igual ao número de linhas de `m2` (2). A matriz resultante será (2x2).

Cada elemento da matriz resultante é obtido pelo produto escalar da linha correspondente da primeira matriz pela coluna correspondente da segunda matriz.

In [16]:
# Cálculo do elemento (0,0)
elemento_0_0 = m1[0, 0] * m2[0, 0] + m1[0, 1] * m2[1, 0]
print(f"Elemento (0,0): ({m1[0, 0]}*{m2[0, 0]}) + ({m1[0, 1]}*{m2[1, 0]}) = {elemento_0_0}")

# Cálculo do elemento (0,1)
elemento_0_1 = m1[0, 0] * m2[0, 1] + m1[0, 1] * m2[1, 1]
print(f"Elemento (0,1): ({m1[0, 0]}*{m2[0, 1]}) + ({m1[0, 1]}*{m2[1, 1]}) = {elemento_0_1}")

# Cálculo do elemento (1,0)
elemento_1_0 = m1[1, 0] * m2[0, 0] + m1[1, 1] * m2[1, 0]
print(f"Elemento (1,0): ({m1[1, 0]}*{m2[0, 0]}) + ({m1[1, 1]}*{m2[1, 0]}) = {elemento_1_0}")

# Cálculo do elemento (1,1)
elemento_1_1 = m1[1, 0] * m2[0, 1] + m1[1, 1] * m2[1, 1]
print(f"Elemento (1,1): ({m1[1, 0]}*{m2[0, 1]}) + ({m1[1, 1]}*{m2[1, 1]}) = {elemento_1_1}")

# Montando a matriz resultante (para comparação com np.dot)
produto_manual = np.array([[elemento_0_0, elemento_0_1],
                           [elemento_1_0, elemento_1_1]])
print("\nMatriz Produto (cálculo manual):\n", produto_manual)

# Comparando com np.dot
produto_np = np.dot(m1, m2)
print("Matriz Produto (usando np.dot):\n", produto_np)

# Verificando se os resultados são iguais
print("\nResultados são iguais?", np.array_equal(produto_manual, produto_np))

Elemento (0,0): (1*5) + (2*7) = 19
Elemento (0,1): (1*6) + (2*8) = 22
Elemento (1,0): (3*5) + (4*7) = 43
Elemento (1,1): (3*6) + (4*8) = 50

Matriz Produto (cálculo manual):
 [[19 22]
 [43 50]]
Matriz Produto (usando np.dot):
 [[19 22]
 [43 50]]

Resultados são iguais? True
