In [1]:
import numpy as np

class MLP_XOR:
    def __init__(self):
        # Pesos e biases ajustados para resolver XOR
        # Baseado na solução clássica com duas camadas ocultas

        # Camada 1: Entrada (2) → Oculta1 (2 neurônios)
        self.W1 = np.array([[20.0, -20.0],
                           [-20.0, 20.0]])
        self.b1 = np.array([-10.0, -10.0])

        # Camada 2: Oculta1 (2) → Oculta2 (2 neurônios)
        self.W2 = np.array([[20.0, 20.0],
                           [0.0, 0.0]])
        self.b2 = np.array([-30.0, 0.0])

        # Camada 3: Oculta2 (2) → Saída (1 neurônio)
        self.W3 = np.array([[20.0],
                           [0.0]])
        self.b3 = np.array([-10.0])

    def sigmoid(self, x):
        """Função de ativação sigmoid"""
        return 1 / (1 + np.exp(-x))

    def forward(self, X):
        """Propagação direta (forward pass)"""
        print(f"Entrada: {X}")

        # Camada 1: Entrada → Oculta1
        z1 = np.dot(X, self.W1.T) + self.b1
        a1 = self.sigmoid(z1)
        print(f"\nCamada Oculta 1:")
        print(f"  z1 = {X}·W1.T + b1 = {z1}")
        print(f"  a1 = sigmoid(z1) = {a1}")

        # Camada 2: Oculta1 → Oculta2
        z2 = np.dot(a1, self.W2.T) + self.b2
        a2 = self.sigmoid(z2)
        print(f"\nCamada Oculta 2:")
        print(f"  z2 = a1·W2.T + b2 = {z2}")
        print(f"  a2 = sigmoid(z2) = {a2}")

        # Camada 3: Oculta2 → Saída
        z3 = np.dot(a2, self.W3) + self.b3
        a3 = self.sigmoid(z3)
        print(f"\nCamada de Saída:")
        print(f"  z3 = a2·W3 + b3 = {z3}")
        print(f"  a3 = sigmoid(z3) = {a3}")

        # Decisão final
        output = 1 if a3 > 0.5 else 0
        print(f"  Saída final: {output}")

        return output, a3

In [2]:
# Criar a MLP
mlp = MLP_XOR()

print("=== MLP PARA PORTA XOR ===")
print("Arquitetura: 2-2-2-1")
print("\nPesos e biases otimizados:")

print("\nCamada 1 (Entrada → Oculta1):")
print(f"W1 = \n{mlp.W1}")
print(f"b1 = {mlp.b1}")

print("\nCamada 2 (Oculta1 → Oculta2):")
print(f"W2 = \n{mlp.W2}")
print(f"b2 = {mlp.b2}")

print("\nCamada 3 (Oculta2 → Saída):")
print(f"W3 = \n{mlp.W3}")
print(f"b3 = {mlp.b3}")

=== MLP PARA PORTA XOR ===
Arquitetura: 2-2-2-1

Pesos e biases otimizados:

Camada 1 (Entrada → Oculta1):
W1 = 
[[ 20. -20.]
 [-20.  20.]]
b1 = [-10. -10.]

Camada 2 (Oculta1 → Oculta2):
W2 = 
[[20. 20.]
 [ 0.  0.]]
b2 = [-30.   0.]

Camada 3 (Oculta2 → Saída):
W3 = 
[[20.]
 [ 0.]]
b3 = [-10.]


In [3]:
# Testar a porta XOR
entradas = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

print("\n" + "="*70)
print("TESTES DA PORTA XOR")
print("="*70)

resultados = []
for i, entrada in enumerate(entradas):
    print(f"\n--- Teste {i+1} ---")
    saida, valor_sigmoid = mlp.forward(entrada)
    resultados.append((entrada, saida, valor_sigmoid[0]))

print("\n" + "="*70)
print("TABELA VERDADE FINAL")
print("="*70)
print("Entrada | Saída | Valor Sigmoid | XOR Esperado | ✓/✗")
print("---------------------------------------------------")
esperado = [0, 1, 1, 0]  # XOR real
for i, (entrada, saida, sigmoid_val) in enumerate(resultados):
    correto = "✓" if saida == esperado[i] else "✗"
    print(f"  {entrada}   |   {saida}   |   {sigmoid_val:.6f}  |      {esperado[i]}      |  {correto}")


TESTES DA PORTA XOR

--- Teste 1 ---
Entrada: [0 0]

Camada Oculta 1:
  z1 = [0 0]·W1.T + b1 = [-10. -10.]
  a1 = sigmoid(z1) = [4.53978687e-05 4.53978687e-05]

Camada Oculta 2:
  z2 = a1·W2.T + b2 = [-29.99818409   0.        ]
  a2 = sigmoid(z2) = [9.37463105e-14 5.00000000e-01]

Camada de Saída:
  z3 = a2·W3 + b3 = [-10.]
  a3 = sigmoid(z3) = [4.53978687e-05]
  Saída final: 0

--- Teste 2 ---
Entrada: [0 1]

Camada Oculta 1:
  z1 = [0 1]·W1.T + b1 = [-30.  10.]
  a1 = sigmoid(z1) = [9.35762297e-14 9.99954602e-01]

Camada Oculta 2:
  z2 = a1·W2.T + b2 = [-10.00090796   0.        ]
  a2 = sigmoid(z2) = [4.53566699e-05 5.00000000e-01]

Camada de Saída:
  z3 = a2·W3 + b3 = [-9.99909287]
  a3 = sigmoid(z3) = [4.54390674e-05]
  Saída final: 0

--- Teste 3 ---
Entrada: [1 0]

Camada Oculta 1:
  z1 = [1 0]·W1.T + b1 = [ 10. -30.]
  a1 = sigmoid(z1) = [9.99954602e-01 9.35762297e-14]

Camada Oculta 2:
  z2 = a1·W2.T + b2 = [-10.00090796   0.        ]
  a2 = sigmoid(z2) = [4.53566699e-05 5.000

In [4]:
print("\n=== EXPLICAÇÃO DA SOLUÇÃO ===")
print("1. Camada Oculta 1:")
print("   - Neurônio 1: Ativa quando x1=1 E x2=0 → (1,0)")
print("   - Neurônio 2: Ativa quando x1=0 E x2=1 → (0,1)")
print("   - Ambos inativos quando (0,0) ou (1,1)")

print("\n2. Camada Oculta 2:")
print("   - Combina as saídas da primeira camada")
print("   - Cria uma representação que pode ser separada linearmente")

print("\n3. Camada de Saída:")
print("   - Produz 1 quando apenas uma entrada é 1")
print("   - Produz 0 quando ambas entradas são iguais")


=== EXPLICAÇÃO DA SOLUÇÃO ===
1. Camada Oculta 1:
   - Neurônio 1: Ativa quando x1=1 E x2=0 → (1,0)
   - Neurônio 2: Ativa quando x1=0 E x2=1 → (0,1)
   - Ambos inativos quando (0,0) ou (1,1)

2. Camada Oculta 2:
   - Combina as saídas da primeira camada
   - Cria uma representação que pode ser separada linearmente

3. Camada de Saída:
   - Produz 1 quando apenas uma entrada é 1
   - Produz 0 quando ambas entradas são iguais


In [5]:
# Versão simplificada para verificação rápida
print("\n" + "="*70)
print("VERIFICAÇÃO RÁPIDA")
print("="*70)

def verificar_xor_simples(entrada):
    # Cálculo direto sem prints detalhados
    z1 = np.dot(entrada, mlp.W1.T) + mlp.b1
    a1 = mlp.sigmoid(z1)
    z2 = np.dot(a1, mlp.W2.T) + mlp.b2
    a2 = mlp.sigmoid(z2)
    z3 = np.dot(a2, mlp.W3) + mlp.b3
    a3 = mlp.sigmoid(z3)
    return 1 if a3 > 0.5 else 0

print("Entrada | Saída MLP | XOR Esperado")
print("----------------------------------")
for entrada in entradas:
    saida = verificar_xor_simples(entrada)
    xor_esperado = entrada[0] ^ entrada[1]  # XOR bit a bit
    print(f"  {entrada}   |     {saida}     |      {xor_esperado}")


VERIFICAÇÃO RÁPIDA
Entrada | Saída MLP | XOR Esperado
----------------------------------
  [0 0]   |     0     |      0
  [0 1]   |     0     |      1
  [1 0]   |     0     |      1
  [1 1]   |     0     |      0
